services:
  react:
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  express:
    container_name: express-dev
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/server
    ports:
      - "5000:5000"
    command: ["npm", "start"]